### ISSUE TITLE
INSTALLATION

### ISSUE THREAD

**Issue by DAVIEN001** [USA-RedDragon/ses-email-service#183]
is this tool for increasing ses smtp daily limit?

if yes, can you please assist me with the installation as i have few questions.

**Comment by USA-RedDragon** [comment]
> is this tool for increasing ses smtp daily limit?

No, this tool is to assist users with many different SMTP workloads in ensuring they maintain compliant with the SES per-second and per-hour rate limits as well as the requirements to handle bounces and complaints.

If you need a higher daily limit, AWS allows users to [request a quota increase via the Service Quotas console](https://docs.aws.amazon.com/ses/latest/dg/manage-sending-quotas-request-increase.html#user-requested-increased-sending-quotas)
